version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: battery-passport-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - battery-passport-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: battery-passport-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - battery-passport-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: battery-passport-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - battery-passport-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: battery-passport-auth-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/battery-passport?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - mongodb
    networks:
      - battery-passport-network

  # Battery Passport Service
  passport-service:
    build:
      context: ./services/passport-service
      dockerfile: Dockerfile
    container_name: battery-passport-passport-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/battery-passport?authSource=admin
      - KAFKA_BROKERS=kafka:29092
      - AUTH_SERVICE_URL=http://auth-service:3001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - mongodb
      - kafka
      - auth-service
    networks:
      - battery-passport-network

  # Document Service
  document-service:
    build:
      context: ./services/document-service
      dockerfile: Dockerfile
    container_name: battery-passport-document-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/battery-passport?authSource=admin
      - AUTH_SERVICE_URL=http://auth-service:3001
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - mongodb
      - auth-service
    networks:
      - battery-passport-network

  # Notification Service
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: battery-passport-notification-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - battery-passport-network

volumes:
  mongodb_data:

networks:
  battery-passport-network:
    driver: bridge 